import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { signIn, useSession } from 'next-auth/react';

import { SignInButton } from '../components/Buttons'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const {data: session} = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Nubank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session ? (
        <main className={styles.main}>
          <h3>Bem-vindo {session.user?.name}</h3>
        </main>
      ) : (
        <main className={styles.main}>
          {session }
          <img src='/nubanklogo.svg' alt='nubank'/>
          <SignInButton onClick={() => signIn('github')} />
        </main>
      )}
    </div>
  )
}

export default Home
